name: troppical-build

on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]

jobs:
  Windows-build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Bump version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          $NEW_VERSION="${{ github.ref_name }}"
          (Get-Content troppical.py) -replace 'version = ".*"', "version = `"$NEW_VERSION`"" | Set-Content troppical.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add troppical.py
          git commit -m "Update version to $NEW_VERSION"
          git push origin HEAD:master --force --follow-tags --verbose
        shell: pwsh

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\pyinstaller\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: pip install pyqt6 pyinstaller pywin32 requests

      - name: Build
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/bin
          pyinstaller --clean --onefile --icon=icon.ico --add-data "icon.ico;." --windowed troppical.py

      - name: Upload troppical
        uses: actions/upload-artifact@v4
        with:
          name: troppical-nightly
          path: ${{ github.workspace }}/dist/troppical.exe

  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          cd android/
          chmod +x gradlew
          ./gradlew assembleDebug
          cd ../..

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

  release:
    needs: [Windows-build, android-build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/troppical-nightly/troppical.exe
          asset_name: troppical.exe
          asset_content_type: application/octet-stream

      - name: Upload Android Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/app-debug/app-debug.apk
          asset_name: troppical.apk
          asset_content_type: application/vnd.android.package-archive